site_name: RFQuack
repo_url: https://github.com/rfquack/RFQuack
nav:
  - "Welcome!": "index.md"
  - "Install":
      - "Grab RFQuack": "usage/download.md"
      - "Software Prerequisites": "usage/dependencies.md"
      - "RFQuack Setup": "usage/setup.md"
      - "Build RFQuack": "usage/build.md"
      - "Flash Your Board": "usage/flash.md"
  - "Usage":
      - "Command Line Interface": "clients/cli.md"
  - "Hardware":
      - "Boards": "hardware/boards.md"
      - "Radios": "hardware/radios.md"
  - "Modules":
      - "Overview": "modules/overview.md"
      - "Built-in Modules":
          - "Radio Module": "modules/builtin/radio-module.md"
          - "Packet Filter": "modules/builtin/packet-filter.md"
          - "Packet Repeater": "modules/builtin/packet-repeater.md"
          - "Packet Manipulator": "modules/builtin/packet-manipulator.md"
          - "Frequency Scanner": "modules/builtin/frequency-scanner.md"
          - "Auto Tuning": "modules/builtin/auto-tuning.md"
          - "MouseJack": "modules/builtin/mousejack.md"
          - "RollJam": "modules/builtin/rolljam.md"
      - "Custom Modules":
          - "Interface": "modules/custom/api.md"
          - "Make a Custom Module": "modules/custom/howto.md"
  - "Architecture": "architecture.md"
  - "Support":
      - "F.A.Q": "support/faq.md"
      - "Community": "support/community.md"
theme:
  name: material
  favicon: imgs/favicon/favicon.ico
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.sections
    - toc.follow
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: imgs/logo-round-nobg.png
  plugins:
    - social
    - git-revision-date-localized:
        enable_creation_date: true
markdown_extensions:
  - def_list
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
